/**
 * TypeScript port of GroundingVerifier.kt.
 *
 * Lightweight post-generation hallucination guard: tokenizes the model's answer into content-word unigrams and
 * checks what fraction of them appear verbatim in any of the retrieved source chunks. Below the threshold, the
 * orchestrator discards the generated answer and falls back to showing the top retrieved chunk verbatim.
 *
 * Identical algorithm to the Kotlin original so behavior matches the existing 5 JUnit cases.
 */

/** Default unigram-overlap threshold - hand-picked to allow natural paraphrase while rejecting invention. */
export const DEFAULT_THRESHOLD = 0.4

/** Lower threshold the orchestrator actually uses, since summary-style answers paraphrase and reduce overlap. */
export const SUMMARY_THRESHOLD = 0.3

/** English stopwords stripped before overlap computation so common function words don't carry the ratio. */
const STOPWORDS = new Set<string>([
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being", "and", "or", "but", "if", "then",
    "to", "of", "in", "on", "for", "with", "by", "at", "as", "from", "into", "about", "it", "its", "this",
    "that", "these", "those", "you", "your", "yours", "we", "our", "ours", "they", "them", "their", "theirs",
    "he", "she", "him", "her", "his", "hers", "i", "me", "my", "mine", "not", "no", "yes", "do", "does",
    "did", "doing", "done", "have", "has", "had", "having", "will", "would", "should", "could", "can", "may",
    "might", "must", "shall", "so", "than", "too", "very", "just", "also", "such", "only", "some", "any",
])

/**
 * Compute the unigram overlap ratio between `answer` and the union of `context` chunks.
 *
 * @param answer Text generated by the LLM whose grounding is being measured.
 * @param context Retrieved doc/code excerpts the answer is supposed to draw from. Each entry is tokenized
 *   independently and unioned into one set, so order does not matter.
 * @returns 1.0 when `answer` has no content tokens (nothing trivially matches), otherwise the fraction of
 *   answer tokens that appear in any context chunk, in [0, 1].
 */
export function overlap(answer: string, context: string[]): number {
    const answerTokens = contentTokens(answer)
    if (answerTokens.size === 0) return 1
    const contextTokens = new Set<string>()
    for (const c of context) for (const t of contentTokens(c)) contextTokens.add(t)
    let matched = 0
    for (const t of answerTokens) if (contextTokens.has(t)) matched += 1
    return matched / answerTokens.size
}

/**
 * Convenience predicate: `true` when `overlap` meets or exceeds `threshold`.
 *
 * The Chat page does not call this directly because it needs the raw overlap value to display in the mode
 * label; this helper exists for future call sites that only need a yes/no answer.
 *
 * @param answer Generated text whose grounding is being judged.
 * @param context Source excerpts the answer is supposed to draw from.
 * @param threshold Minimum acceptable overlap, defaulted to `DEFAULT_THRESHOLD`. Pass `SUMMARY_THRESHOLD` for
 *   summary-style answers, where paraphrase reduces token reuse.
 * @returns `true` when the `overlap` ratio is greater than or equal to `threshold`.
 */
export function isGrounded(answer: string, context: string[], threshold: number = DEFAULT_THRESHOLD): boolean {
    return overlap(answer, context) >= threshold
}

/**
 * Tokenize `text` into a set of lowercased content-word unigrams. Single-character tokens and members of
 * `STOPWORDS` are dropped so the overlap ratio reflects meaningful matches rather than function-word noise.
 *
 * Identical to the Kotlin implementation in `GroundingVerifier.kt` so behavior matches the existing JUnit cases.
 *
 * @param text Arbitrary input text to tokenize. Casing and surrounding punctuation do not matter.
 * @returns Set of distinct content-word tokens (length > 1, not in `STOPWORDS`) in lowercase.
 */
function contentTokens(text: string): Set<string> {
    const out = new Set<string>()
    const lower = text.toLowerCase()
    let buf = ""
    for (const ch of lower) {
        if (isLetterOrDigit(ch)) {
            buf += ch
        } else {
            if (buf.length > 0) {
                if (buf.length > 1 && !STOPWORDS.has(buf)) out.add(buf)
                buf = ""
            }
        }
    }
    if (buf.length > 1 && !STOPWORDS.has(buf)) out.add(buf)
    return out
}

/**
 * Unicode-aware letter-or-digit test used to split content tokens. Matches `Character.isLetterOrDigit` on the
 * Kotlin side so identical inputs produce identical token sets across the two implementations.
 *
 * @param ch Single character from the iteration in `contentTokens`.
 * @returns `true` when `ch` is any Unicode letter or digit; `false` for whitespace, punctuation, and symbols.
 */
function isLetterOrDigit(ch: string): boolean {
    return /[\p{L}\p{N}]/u.test(ch)
}
