package com.steve1316.uma_android_automation.bot

import com.steve1316.uma_android_automation.bot.Training.Companion.burstExemptFailureChance
import com.steve1316.uma_android_automation.bot.Training.Companion.defaultScoringModeFor
import com.steve1316.uma_android_automation.bot.Training.Companion.failsExpectedValueGate
import com.steve1316.uma_android_automation.bot.Training.Companion.formatDecisionTrace
import com.steve1316.uma_android_automation.bot.Training.Companion.formatScoreBreakdown
import com.steve1316.uma_android_automation.bot.Training.Companion.formatSelectionRankingLine
import com.steve1316.uma_android_automation.bot.Training.Companion.friendshipKeyFactors
import com.steve1316.uma_android_automation.bot.Training.Companion.statEfficiencyKeyFactors
import com.steve1316.uma_android_automation.bot.Training.Companion.unityCupKeyFactors
import com.steve1316.uma_android_automation.bot.Training.Companion.witOnlyKeyFactor
import com.steve1316.uma_scoring.RawScoreBreakdown
import com.steve1316.uma_android_automation.bot.Training.TrainingConfig
import com.steve1316.uma_android_automation.bot.Training.TrainingOption
import com.steve1316.uma_android_automation.types.DateMonth
import com.steve1316.uma_android_automation.types.DatePhase
import com.steve1316.uma_android_automation.types.DateYear
import com.steve1316.uma_android_automation.types.GameDate
import com.steve1316.uma_android_automation.types.StatName
import com.steve1316.uma_android_automation.utils.CustomImageUtils.BarFillResult
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

/**
 * Unit tests for the training-selection explanation layer: scoring-mode resolution and per-mode key-factor generation.
 * These guard against the class of bug where the explanation text is generated by logic that does not match the scorer that actually ran.
 */
@DisplayName("Training Explanation Tests")
class TrainingExplanationTest {
    private fun option(
        name: StatName = StatName.SPEED,
        statGains: Map<StatName, Int> = mapOf(StatName.SPEED to 15, StatName.POWER to 5),
        relationshipBars: ArrayList<BarFillResult> = arrayListOf(),
        numRainbow: Int = 0,
        extras: Map<String, Any?> = emptyMap(),
    ): TrainingOption = TrainingOption(name = name, statGains = statGains, failureChance = 5, relationshipBars = relationshipBars, numRainbow = numRainbow, extras = extras)

    private fun bar(color: String, fill: Double): BarFillResult = BarFillResult(statName = StatName.SPEED, fillPercent = fill, filledSegments = 2, dominantColor = color)

    private fun config(year: DateYear): TrainingConfig =
        TrainingConfig(
            currentStats = StatName.entries.associateWith { 120 },
            statPrioritization = listOf(StatName.SPEED, StatName.STAMINA, StatName.POWER, StatName.WIT, StatName.GUTS),
            eventChoiceStatPriority = listOf(StatName.SPEED),
            summerTrainingStatPriority = listOf(StatName.SPEED),
            statTargets = StatName.entries.associateWith { 600 },
            currentDate = GameDate(year = year, month = DateMonth.JANUARY, phase = DatePhase.EARLY),
            scenario = "URA Finale",
            enableRainbowTrainingBonus = true,
            trainingOptions = emptyList(),
        )

    @Test
    @DisplayName("defaultScoringModeFor maps pre-debut and Junior to FRIENDSHIP, later years to STAT_EFFICIENCY")
    fun testDefaultScoringModeMapping() {
        assertEquals(TrainingScoringMode.FRIENDSHIP, defaultScoringModeFor(bIsPreDebut = true, year = DateYear.JUNIOR))
        assertEquals(TrainingScoringMode.FRIENDSHIP, defaultScoringModeFor(bIsPreDebut = false, year = DateYear.JUNIOR))
        assertEquals(TrainingScoringMode.STAT_EFFICIENCY, defaultScoringModeFor(bIsPreDebut = false, year = DateYear.CLASSIC))
        assertEquals(TrainingScoringMode.STAT_EFFICIENCY, defaultScoringModeFor(bIsPreDebut = false, year = DateYear.SENIOR))
    }

    @Test
    @DisplayName("WIT-only factor fires only when WIT was the sole gate-passing stat and others were skipped")
    fun testWitOnlyKeyFactor() {
        assertNotNull(
            witOnlyKeyFactor(StatName.WIT, setOf(StatName.WIT), anySkipped = true, energy = 18),
            "WIT alone passing the gate with others skipped should produce a WIT-only factor",
        )
        assertTrue(witOnlyKeyFactor(StatName.WIT, setOf(StatName.WIT), anySkipped = true, energy = 18)!!.contains("18%"), "The factor should state the energy level")
        assertNull(witOnlyKeyFactor(StatName.SPEED, setOf(StatName.SPEED), anySkipped = true, energy = 18), "A non-WIT selection must not produce the WIT-only factor")
        assertNull(witOnlyKeyFactor(StatName.WIT, setOf(StatName.WIT, StatName.SPEED), anySkipped = true, energy = 18), "If another stat also passed, WIT was not the only option")
        assertNull(witOnlyKeyFactor(StatName.WIT, setOf(StatName.WIT), anySkipped = false, energy = 90), "With nothing skipped, WIT was a genuine pick, not a fallback")
    }

    @Test
    @DisplayName("Friendship key factors report blue and green bars to build")
    fun testFriendshipKeyFactorsReachable() {
        val selected = option(relationshipBars = arrayListOf(bar("blue", 40.0), bar("green", 30.0)))
        val factors = friendshipKeyFactors(selected)
        assertTrue(factors.any { it.contains("blue") && it.contains("green") }, "Expected a blue/green bar factor, got: $factors")
    }

    @Test
    @DisplayName("Anticipatory factor fires only above the real fill threshold, matching the scorer")
    fun testAnticipatoryFactorThresholdAlignment() {
        val cfg = config(DateYear.CLASSIC)
        val below = option(relationshipBars = arrayListOf(bar("blue", 48.0)))
        val above = option(relationshipBars = arrayListOf(bar("blue", 55.0)))
        assertFalse(statEfficiencyKeyFactors(cfg, below).any { it.contains("anticipatory", ignoreCase = true) }, "48% blue bar must not report the anticipatory multiplier (threshold is 50%)")
        assertTrue(statEfficiencyKeyFactors(cfg, above).any { it.contains("anticipatory", ignoreCase = true) }, "55% blue bar should report the anticipatory multiplier")
    }

    @Test
    @DisplayName("High main-stat gain factor uses honest bonus wording, not undetected-rainbow")
    fun testMainStatFactorHonestWording() {
        val cfg = config(DateYear.CLASSIC)
        val selected = option(statGains = mapOf(StatName.SPEED to 35))
        val factors = statEfficiencyKeyFactors(cfg, selected)
        assertTrue(factors.any { it.contains("main-stat bonus", ignoreCase = true) }, "Expected honest main-stat bonus wording, got: $factors")
        assertFalse(factors.any { it.contains("undetected rainbow", ignoreCase = true) }, "Must not claim an undetected rainbow bonus")
    }

    @Test
    @DisplayName("Ranking line reports absolute scores, a ratio, and the mode - not an ambiguous point difference")
    fun testRankingLineFormat() {
        val line = formatSelectionRankingLine(StatName.SPEED, 812.40, StatName.POWER, 615.20, "Stat Efficiency (Year 2+)", 0)
        assertTrue(line.contains("Selected SPEED"), line)
        assertTrue(line.contains("over runner-up POWER"), line)
        assertTrue(line.contains("1.32x higher"), line)
        assertTrue(line.contains("[mode: Stat Efficiency (Year 2+)]"), line)
        assertFalse(line.contains("points"), "Ranking line must not use the ambiguous 'points' wording: $line")
    }

    @Test
    @DisplayName("Decision trace lists the mode, the selection, and every candidate score highest-first")
    fun testDecisionTraceFormat() {
        val line = formatDecisionTrace("Unity Cup (Spirit Gauge)", StatName.GUTS, mapOf(StatName.POWER to 196.25, StatName.GUTS to 746.90))
        assertTrue(line.contains("Unity Cup (Spirit Gauge)"), line)
        assertTrue(line.contains("selected=GUTS"), line)
        assertTrue(line.contains("GUTS=746.90"), line)
        assertTrue(line.contains("POWER=196.25"), line)
        // Highest score should appear before the lower one.
        assertTrue(line.indexOf("GUTS=746.90") < line.indexOf("POWER=196.25"), "Scores should be ranked highest-first: $line")
    }

    @Test
    @DisplayName("Score breakdown shows each weighted factor and the applied multipliers")
    fun testScoreBreakdownFormat() {
        val breakdown = RawScoreBreakdown(statScoreWeighted = 100.0, relationshipScoreWeighted = 10.0, miscScoreWeighted = 15.0, rainbowMultiplier = 2.0, anticipatoryMultiplier = 1.10, total = 275.0)
        val line = formatScoreBreakdown(StatName.SPEED, breakdown)
        assertTrue(line.contains("SPEED"), line)
        assertTrue(line.contains("statEff=100.00"), line)
        assertTrue(line.contains("2.00") && line.contains("1.10"), line)
        assertTrue(line.contains("275.00"), line)
    }

    @Test
    @DisplayName("Ranking line omits the ratio when the runner-up score is non-positive and notes excluded trainings")
    fun testRankingLineEdgeCases() {
        val zeroRunnerUp = formatSelectionRankingLine(StatName.SPEED, 400.0, StatName.WIT, 0.0, "Unity Cup (Spirit Gauge)", 2)
        assertFalse(zeroRunnerUp.contains("x higher"), "No ratio when runner-up score is 0: $zeroRunnerUp")
        assertTrue(zeroRunnerUp.contains("2 training(s) excluded"), zeroRunnerUp)
    }

    @Test
    @DisplayName("Expected-value gate skips only when total gain is below the multiple of fail chance, above the min threshold")
    fun testExpectedValueGate() {
        // Community rule source: https://docs.google.com/document/d/11X2P7pLuh-k9E7PhRiD20nDX22rNWtCpC1S4IMx_8pQ/edit?tab=t.chehxs4igdlt ("if the stats you gain are less than double the fail chance, don't do it").
        // Community rule: 27% fail needs 54+ total gain; 51 total is poor value -> gated.
        assertTrue(failsExpectedValueGate(totalStatGain = 51, failureChance = 27, gainPerFailPercent = 2.0, minFailureChance = 10))
        // Exactly 2x the fail chance is acceptable -> not gated.
        assertFalse(failsExpectedValueGate(totalStatGain = 54, failureChance = 27, gainPerFailPercent = 2.0, minFailureChance = 10))
        // Below the min-failure threshold the rule never fires, even for tiny gains at low risk.
        assertFalse(failsExpectedValueGate(totalStatGain = 5, failureChance = 8, gainPerFailPercent = 2.0, minFailureChance = 10))
    }

    @Test
    @DisplayName("Unity Cup burst exemption raises the failure ceiling only when a gauge is ready and the setting is above the base")
    fun testBurstExemptFailureChance() {
        // Default setting (0) is a pure pass-through even with a gauge ready.
        assertEquals(15, burstExemptFailureChance(baseFailureChance = 15, readyToBurst = 1, burstMax = 0))
        // No gauge ready: the exemption never applies regardless of the setting.
        assertEquals(15, burstExemptFailureChance(baseFailureChance = 15, readyToBurst = 0, burstMax = 40))
        // Gauge ready and setting above base: the ceiling is raised to the burst max.
        assertEquals(40, burstExemptFailureChance(baseFailureChance = 15, readyToBurst = 1, burstMax = 40))
        // Setting below the base never lowers the ceiling.
        assertEquals(30, burstExemptFailureChance(baseFailureChance = 30, readyToBurst = 2, burstMax = 20))
        // No extreme burst ready: readyToExtremeBurst defaults to 0 and behaves exactly as above.
        assertEquals(15, burstExemptFailureChance(baseFailureChance = 15, readyToBurst = 0, burstMax = 0, readyToExtremeBurst = 0))
        // An extreme burst ready always raises the ceiling to 100, overriding both the base and the normal burst max.
        assertEquals(100, burstExemptFailureChance(baseFailureChance = 15, readyToBurst = 0, burstMax = 0, readyToExtremeBurst = 1))
        // Extreme burst still wins even when a normal burst is also ready.
        assertEquals(100, burstExemptFailureChance(baseFailureChance = 15, readyToBurst = 1, burstMax = 40, readyToExtremeBurst = 1))
    }

    @Test
    @DisplayName("Unity Cup key factors reflect gauge burst/fill and never claim an anticipatory rainbow multiplier")
    fun testUnityCupKeyFactorsNoAnticipatory() {
        val burst = option(extras = mapOf("spiritGaugesReadyToBurst" to 1, "spiritGaugesCanFill" to 0))
        val fill = option(extras = mapOf("spiritGaugesReadyToBurst" to 0, "spiritGaugesCanFill" to 1))
        val burstFactors = unityCupKeyFactors(burst)
        val fillFactors = unityCupKeyFactors(fill)
        assertTrue(burstFactors.any { it.contains("burst", ignoreCase = true) }, "Expected a burst factor, got: $burstFactors")
        assertTrue(fillFactors.any { it.contains("fill", ignoreCase = true) || it.contains("Spirit Gauge", ignoreCase = true) }, "Expected a fill factor, got: $fillFactors")
        val all = burstFactors + fillFactors
        assertFalse(all.any { it.contains("anticipatory", ignoreCase = true) || it.contains("rainbow multiplier", ignoreCase = true) }, "Unity factors must not mention the anticipatory/rainbow multiplier")
    }
}
