package com.steve1316.uma_android_automation.bot

import com.steve1316.uma_android_automation.bot.Training.Companion.defaultScoringModeFor
import com.steve1316.uma_android_automation.bot.Training.Companion.friendshipKeyFactors
import com.steve1316.uma_android_automation.bot.Training.Companion.statEfficiencyKeyFactors
import com.steve1316.uma_android_automation.bot.Training.Companion.unityCupKeyFactors
import com.steve1316.uma_android_automation.bot.Training.TrainingConfig
import com.steve1316.uma_android_automation.bot.Training.TrainingOption
import com.steve1316.uma_android_automation.types.DateMonth
import com.steve1316.uma_android_automation.types.DatePhase
import com.steve1316.uma_android_automation.types.DateYear
import com.steve1316.uma_android_automation.types.GameDate
import com.steve1316.uma_android_automation.types.StatName
import com.steve1316.uma_android_automation.utils.CustomImageUtils.BarFillResult
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

/**
 * Unit tests for the training-selection explanation layer: scoring-mode resolution and per-mode key-factor generation.
 * These guard against the class of bug where the explanation text is generated by logic that does not match the scorer that actually ran.
 */
@DisplayName("Training Explanation Tests")
class TrainingExplanationTest {
    private fun option(
        name: StatName = StatName.SPEED,
        statGains: Map<StatName, Int> = mapOf(StatName.SPEED to 15, StatName.POWER to 5),
        relationshipBars: ArrayList<BarFillResult> = arrayListOf(),
        numRainbow: Int = 0,
        extras: Map<String, Any?> = emptyMap(),
    ): TrainingOption = TrainingOption(name = name, statGains = statGains, failureChance = 5, relationshipBars = relationshipBars, numRainbow = numRainbow, extras = extras)

    private fun bar(color: String, fill: Double): BarFillResult = BarFillResult(statName = StatName.SPEED, fillPercent = fill, filledSegments = 2, dominantColor = color)

    private fun config(year: DateYear): TrainingConfig =
        TrainingConfig(
            currentStats = StatName.entries.associateWith { 120 },
            statPrioritization = listOf(StatName.SPEED, StatName.STAMINA, StatName.POWER, StatName.WIT, StatName.GUTS),
            eventChoiceStatPriority = listOf(StatName.SPEED),
            summerTrainingStatPriority = listOf(StatName.SPEED),
            statTargets = StatName.entries.associateWith { 600 },
            currentDate = GameDate(year = year, month = DateMonth.JANUARY, phase = DatePhase.EARLY),
            scenario = "URA Finale",
            enableRainbowTrainingBonus = true,
            trainingOptions = emptyList(),
        )

    @Test
    @DisplayName("defaultScoringModeFor maps pre-debut and Junior to FRIENDSHIP, later years to STAT_EFFICIENCY")
    fun testDefaultScoringModeMapping() {
        assertEquals(TrainingScoringMode.FRIENDSHIP, defaultScoringModeFor(bIsPreDebut = true, year = DateYear.JUNIOR))
        assertEquals(TrainingScoringMode.FRIENDSHIP, defaultScoringModeFor(bIsPreDebut = false, year = DateYear.JUNIOR))
        assertEquals(TrainingScoringMode.STAT_EFFICIENCY, defaultScoringModeFor(bIsPreDebut = false, year = DateYear.CLASSIC))
        assertEquals(TrainingScoringMode.STAT_EFFICIENCY, defaultScoringModeFor(bIsPreDebut = false, year = DateYear.SENIOR))
    }

    @Test
    @DisplayName("Friendship key factors report blue and green bars to build")
    fun testFriendshipKeyFactorsReachable() {
        val selected = option(relationshipBars = arrayListOf(bar("blue", 40.0), bar("green", 30.0)))
        val factors = friendshipKeyFactors(selected)
        assertTrue(factors.any { it.contains("blue") && it.contains("green") }, "Expected a blue/green bar factor, got: $factors")
    }

    @Test
    @DisplayName("Anticipatory factor fires only above the real fill threshold, matching the scorer")
    fun testAnticipatoryFactorThresholdAlignment() {
        val cfg = config(DateYear.CLASSIC)
        val below = option(relationshipBars = arrayListOf(bar("blue", 48.0)))
        val above = option(relationshipBars = arrayListOf(bar("blue", 55.0)))
        assertFalse(statEfficiencyKeyFactors(cfg, below).any { it.contains("anticipatory", ignoreCase = true) }, "48% blue bar must not report the anticipatory multiplier (threshold is 50%)")
        assertTrue(statEfficiencyKeyFactors(cfg, above).any { it.contains("anticipatory", ignoreCase = true) }, "55% blue bar should report the anticipatory multiplier")
    }

    @Test
    @DisplayName("High main-stat gain factor uses honest bonus wording, not undetected-rainbow")
    fun testMainStatFactorHonestWording() {
        val cfg = config(DateYear.CLASSIC)
        val selected = option(statGains = mapOf(StatName.SPEED to 35))
        val factors = statEfficiencyKeyFactors(cfg, selected)
        assertTrue(factors.any { it.contains("main-stat bonus", ignoreCase = true) }, "Expected honest main-stat bonus wording, got: $factors")
        assertFalse(factors.any { it.contains("undetected rainbow", ignoreCase = true) }, "Must not claim an undetected rainbow bonus")
    }

    @Test
    @DisplayName("Unity Cup key factors reflect gauge burst/fill and never claim an anticipatory rainbow multiplier")
    fun testUnityCupKeyFactorsNoAnticipatory() {
        val burst = option(extras = mapOf("spiritGaugesReadyToBurst" to 1, "spiritGaugesCanFill" to 0))
        val fill = option(extras = mapOf("spiritGaugesReadyToBurst" to 0, "spiritGaugesCanFill" to 1))
        val burstFactors = unityCupKeyFactors(burst)
        val fillFactors = unityCupKeyFactors(fill)
        assertTrue(burstFactors.any { it.contains("burst", ignoreCase = true) }, "Expected a burst factor, got: $burstFactors")
        assertTrue(fillFactors.any { it.contains("fill", ignoreCase = true) || it.contains("Spirit Gauge", ignoreCase = true) }, "Expected a fill factor, got: $fillFactors")
        val all = burstFactors + fillFactors
        assertFalse(all.any { it.contains("anticipatory", ignoreCase = true) || it.contains("rainbow multiplier", ignoreCase = true) }, "Unity factors must not mention the anticipatory/rainbow multiplier")
    }
}
